### ISSUE TITLE
Suggestion - Instructions for implementing in existing projects

### ISSUE THREAD

**Issue by RobErskine** [ben-rogerson/craft-storybook-starter#1]
Hey Ben!

This looks absolutely rad. Going to start playing with this later today.

Do you think it would be worthwhile to include instructions on how to integrate this into an existing Craft project, instead of how to spin it up with a new install? I have a few ongoing projects I'd love to drop this into, but I'm a little fuzzy about what files I need and where.

Thanks again for this awesome project.

**Comment by ben-rogerson** [comment]
Hey Rob

Great idea about including "drop in" instructions!
I've added them to the [readme](https://github.com/ben-rogerson/craft-storybook-starter#adding-storybook-to-an-existing-craft-project). 
Let me know if you run into any issues - thanks.
